const data=window.GOALS_DATA||[];const charts={};const $=id=>document.getElementById(id);
const fields={equipe:"EQUIPE",comp:"COMPETIÇÃO",adv:"ADVERSÁRIO",mando:"MANDO",autor:"AUTOR DO GOL",origem:"ORIGEM DA JOGADA"};
function val(r,k){return r[k]??"N/A"} function uniq(key){return [...new Set(data.map(r=>val(r,key)).filter(x=>x!==""&&x!=null))].sort((a,b)=>String(a).localeCompare(String(b),"pt-BR"))}
for(const [id,key] of Object.entries(fields)){const s=$(("f"+id.charAt(0).toUpperCase()+id.slice(1)));uniq(key).forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;s.appendChild(o)})}
const filters=Object.keys(fields);
function filtered(){return data.filter(r=>filters.every(id=>{const s=$(("f"+id.charAt(0).toUpperCase()+id.slice(1)));return !s.value||String(val(r,fields[id]))===s.value}))}
function countBy(arr,key){const c={};arr.forEach(r=>{const v=val(r,key);c[v]=(c[v]||0)+1});return Object.entries(c).sort((a,b)=>b[1]-a[1])}
function fmt(n){return n.toLocaleString("pt-BR")}
function chart(id,type,labels,values){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets:[{data:values,borderWidth:1,borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:"#9aa7b4",font:{size:10}},grid:{color:"rgba(255,255,255,.05)"}},y:{beginAtZero:true,ticks:{color:"#9aa7b4",precision:0},grid:{color:"rgba(255,255,255,.05)"}}}}})}
function update(){const d=filtered();const games=new Set(d.map(r=>`${r.DATA}|${r.ADVERSÁRIO}`)).size; $("kpiGoals").textContent=fmt(d.length);$("kpiGames").textContent=fmt(games);$("kpiAvg").textContent=games?(d.length/games).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2}):"0,00";$("kpiHome").textContent=fmt(d.filter(r=>String(val(r,"MANDO")).toLowerCase()==="casa").length);$("kpiAway").textContent=fmt(d.filter(r=>String(val(r,"MANDO")).toLowerCase()==="fora").length);
let bins=[0,0,0,0,0,0];d.forEach(r=>{let m=Number(r.MINUTO)||0;if(m<=15)bins[0]++;else if(m<=30)bins[1]++;else if(m<=45)bins[2]++;else if(m<=60)bins[3]++;else if(m<=75)bins[4]++;else bins[5]++});chart("minuteChart","bar",["0–15","16–30","31–45","46–60","61–75","76–90+"],bins);
let a=countBy(d,"AUTOR DO GOL").slice(0,10);chart("scorerChart","bar",a.map(x=>x[0]),a.map(x=>x[1]));a=countBy(d,"ORIGEM DA JOGADA");chart("originChart","doughnut",a.map(x=>x[0]),a.map(x=>x[1]));a=countBy(d,"ZONA DA FINALIZAÇÃO").filter(x=>x[0]!=="N/A");chart("zoneChart","bar",a.map(x=>x[0]),a.map(x=>x[1]));a=countBy(d,"FORMA DA FINALIZAÇÃO");chart("finishChart","doughnut",a.map(x=>x[0]),a.map(x=>x[1]));a=countBy(d,"COMPETIÇÃO");chart("compChart","bar",a.map(x=>x[0]),a.map(x=>x[1]));
$("kpiAssisted").textContent=fmt(d.filter(r=>val(r,"ASSISTENTE")!=="N/A").length);$("kpiUnassisted").textContent=fmt(d.filter(r=>val(r,"ASSISTENTE")==="N/A").length);$("kpiAssistants").textContent=fmt(new Set(d.map(r=>val(r,"ASSISTENTE")).filter(x=>x!=="N/A")).size);$("kpiThird").textContent=fmt(d.filter(r=>val(r,"TERÇO DA ASSISTÊNCIA")==="3 - Último terço").length);
a=countBy(d,"ASSISTENTE").filter(x=>x[0]!=="N/A").slice(0,10);chart("assistantChart","bar",a.map(x=>x[0]),a.map(x=>x[1]));a=countBy(d,"TIPO DE PASSE/AÇÃO DA ASSISTÊNCIA").filter(x=>x[0]!=="N/A");chart("passChart","bar",a.map(x=>x[0]),a.map(x=>x[1]));a=countBy(d,"ZONA DA ASSISTÊNCIA").filter(x=>x[0]!=="N/A");chart("assistZoneChart","bar",a.map(x=>x[0]),a.map(x=>x[1]));a=countBy(d,"TERÇO DA ASSISTÊNCIA");chart("thirdChart","doughnut",a.map(x=>x[0]),a.map(x=>x[1]));renderTable(d)}
function renderTable(d){$("rowCount").textContent=`${d.length} registros`;const cols=["DATA","ADVERSÁRIO","RODADA","RESULTADO","MANDO","MINUTO","AUTOR DO GOL","POSIÇÃO DO AUTOR","ZONA DA FINALIZAÇÃO","ASSISTENTE","ZONA DA ASSISTÊNCIA","TIPO DE PASSE/AÇÃO DA ASSISTÊNCIA","ORIGEM DA JOGADA","FORMA DA FINALIZAÇÃO"];$("thead").innerHTML="<tr>"+cols.map(c=>`<th>${c}</th>`).join("")+"</tr>";$("tbody").innerHTML=d.map(r=>"<tr>"+cols.map(c=>`<td>${val(r,c)}</td>`).join("")+"</tr>").join("")}
document.querySelectorAll(".filters select").forEach(s=>s.addEventListener("change",update));$("reset").onclick=()=>{document.querySelectorAll(".filters select").forEach(s=>s.value="");update()};
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));b.classList.add("active");const p=b.dataset.page;["gols","assistencias","dados"].forEach(x=>$(x+"Page").classList.toggle("hidden",x!==p));$("pageTitle").textContent=p==="gols"?"Análise de Gols":p==="assistencias"?"Análise de Assistências":"Base de Dados"});
update();
